defaults:
  - synthetic_seq_train
  - _self_

logger:
  project: "pattern-search-synthetic-sequences"
  name: "reverse_task_${now:%Y-%m-%d}_${now:%H-%M-%S}"
  tags: ["pattern_search", "transformer", "synthetic_sequences", "reverse"]

# Override datasets to use reverse function instead of sort
train_dataset:
  _target_: src.synthetic_seq_data.SyntheticSequenceDataset
  n_samples: 100
  min_seq_len: 3
  max_seq_len: 6
  vocab_size: 15  # Use integers 0-14 for variety
  ground_truth_fn:
    _target_: src.synthetic_seq_data.reverse_fn
  sep_token: 102
  pad_token: 103

val_dataset:
  _target_: src.synthetic_seq_data.SyntheticSequenceDataset
  n_samples: 30
  min_seq_len: 3
  max_seq_len: 6
  vocab_size: 15
  ground_truth_fn:
    _target_: src.synthetic_seq_data.reverse_fn
  sep_token: 102
  pad_token: 103

test_dataset:
  _target_: src.synthetic_seq_data.SyntheticSequenceDataset
  n_samples: 30
  min_seq_len: 3
  max_seq_len: 6
  vocab_size: 15
  ground_truth_fn:
    _target_: src.synthetic_seq_data.reverse_fn
  sep_token: 102
  pad_token: 103