defaults:
  - hydra: default
  - _self_

save_dir: "logs/synthetic_sequence_adam_tiny/"
seed: 42

logger:
  _target_: lightning.pytorch.loggers.WandbLogger
  entity: null  # Add your wandb entity here
  project: "adam-synthetic-sequences"  # Add your wandb project here
  name: "synthetic_seq_adam_tiny_${now:%Y-%m-%d}_${now:%H-%M-%S}"
  save_dir: ${save_dir}
  offline: True  # Set to False if you want to log to wandb online
  tags: ["adam", "transformer", "synthetic_sequences", "sort", "tiny"]

trainer:
  max_epochs: 1
  enable_progress_bar: True
  log_every_n_steps: 1
  val_check_interval: 500  # More frequent validation for tiny model
  accelerator: "auto"
  devices: 1
  limit_train_batches: null
  limit_val_batches: null

# Tiny transformer model for sorting task
model:
  _target_: transformer.DecoderOnlyTransformer
  vocab_size: 110  # 0-19 (vocab) + 102 (sep) + 103 (pad) + extra room
  d_model: 128 
  n_layers: 2
  n_heads: 4
  d_ff: 256 
  max_len: 128
  dropout: 0.1

task:
  _target_: adam_task.AdamTask
  model: ${model}
  pad_token_id: 103
  sep_token_id: 102
  learning_rate: 1e-4  # Slightly higher LR for tiny model
  weight_decay: 0.01   # AdamW weight decay

# Toy dataset - train on length 1-10, test on length 20
train_dataset:
  _target_: synthetic_seq_data.SyntheticSequenceDataset
  n_samples: 1300000
  min_seq_len: 1
  max_seq_len: 5
  vocab_size: 10  # Use integers 0-19
  ground_truth_fn:
    _partial_: true
    _target_: synthetic_seq_data.sort_fn
  sep_token: 102
  pad_token: 103

val_dataset:
  _target_: synthetic_seq_data.SyntheticSequenceDataset
  n_samples: 1000
  min_seq_len: 1
  max_seq_len: 5 
  vocab_size: 10  # Use integers 0-19
  ground_truth_fn:
    _partial_: true
    _target_: synthetic_seq_data.sort_fn
  sep_token: 102
  pad_token: 103

test_dataset:
  _target_: synthetic_seq_data.SyntheticSequenceDataset
  n_samples: 1000
  min_seq_len: 5 
  max_seq_len: 10 
  vocab_size: 10  # Use integers 0-19
  ground_truth_fn:
    _partial_: true
    _target_: synthetic_seq_data.sort_fn
  sep_token: 102
  pad_token: 103

datamodule:
  _target_: synthetic_seq_data.SyntheticSequenceDataModule
  train_dataset: ${train_dataset}
  val_dataset: ${val_dataset}
  test_dataset: ${test_dataset}
  batch_size: 512  # Smaller batch size for toy experiment
  num_workers: 0
  enable_position_shifting: true  # Enable position shifting for length generalization

callbacks:
  early_stopping:
    _target_: lightning.pytorch.callbacks.EarlyStopping
    monitor: val_exact_match
    min_delta: 0.001
    patience: 5
    mode: max
    verbose: True
    stopping_threshold: 0.99  # Stop when validation accuracy reaches 99.5%
  model_checkpoint:
    _target_: lightning.pytorch.callbacks.ModelCheckpoint
    monitor: val_exact_match
    mode: max
    save_top_k: 1
    save_last: False
    filename: "synthetic_seq_adam_tiny_{epoch:02d}_{val_exact_match:.3f}"
    dirpath: ${save_dir}/checkpoints
    verbose: True
    auto_insert_metric_name: False